inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

RSpec/ContextWording:
  AllowedPatterns:
  - とき$

# :: の重複使用を許可
Style/RedundantConstantBase:
  Enabled: false
