query GetComment($id: ID!) {
  comment(id: $id) {
    id
    description
    createdAt
    user {
      id
      name
      image
    }
  }
}

query GetComments($ideaId: ID!) {
  comments(ideaId: $ideaId) {
    id
    description
    createdAt
    user {
      id
      name
      image
    }
  }
}

mutation CreateComment($input: CreateCommentInput!) {
  createComment(input: $input) {
    comment {
      id
      description
    }
    success
    errors
  }
}

mutation UpdateComment($input: UpdateCommentInput!) {
  updateComment(input: $input) {
    comment {
      id
      description
    }
    success
  }
}

mutation DestroyComment($input: DestroyCommentInput!) {
  destroyComment(input: $input) {
    success
  }
}
