query GetIdea($id: ID!) {
  idea(id: $id) {
    id
    name
    iconUrl
    background
    goal
    issue
    wishFunction
    hypothesis
    target
    monetize
    similar
    stance
		note
    draft
    createdAt
    updatedAt
    userId
    productUrl
    githubUrl
    user {
      id
      name
      image
      twitterId
    }
    comments {
      id
      description
      createdAt
      userId
      user {
        name
        image
      }
    }
    ideaTags {
      id
      name
    }
  }
}

query GetIdeas($searchCondition: SearchCondition, $sort: SortCondition) {
  ideas(searchCondition: $searchCondition, sort: $sort) {
    nodes {
      id
      name
      commentsNum
      difficulty
      likesNum
      view
      updatedAt
      publishedAt
      user {
        id
        name
        image
      }
      ideaTags {
        id
        name
      }
      team {
        status
        membersNum
      }
    }
    pageInfo {
      currentPage
      isFirst
      isLast
      nextPage
      per
      prevPage
      totalCount
      totalPages
    }
  }
}

query GetHotIdeas {
  hotIdeas {
    id
    name
    user {
      image
    }
    ideaTags {
      id
      name
    }
  }
}

query GetDeployedIdeas {
  deployedIdeas {
    id
    name
    user {
      image
    }
    ideaTags {
      id
      name
    }
  }
}

query GetActiveTeamIdeas {
  activeTeamIdeas {
    id
    name
    user {
      image
    }
    ideaTags {
      id
      name
    }
  }
}

mutation CreateIdea($input: CreateIdeaInput!) {
  createIdea(input: $input) {
    idea {
      userId
      id
      name
      background
      goal
      target
    }
    success
    errors
  }
}

mutation UpdateIdea($input: UpdateIdeaInput!) {
  updateIdea(input: $input) {
    idea {
      id
      name
      background
      goal
      issue
      hypothesis
      monetize
      similar
      stance
      target
      wishFunction
      githubUrl
      productUrl
      draft
      iconUrl
    }
    success
    errors
  }
}

mutation DestroyIdea($input: DestroyIdeaInput!) {
  destroyIdea(input: $input) {
    success
  }
}

query GetDraftIdeas($page: Int, $per: Int) {
  draftIdeas(page: $page, per: $per) {
    nodes {
      id
      name
      ideaTags {
        id
        name
      }
    }
    pageInfo {
      currentPage
      isFirst
      isLast
      nextPage
      per
      prevPage
      totalCount
      totalPages
    }
  }
}

query GetPublishedIdeas($page: Int, $per: Int, $userId: ID!) {
  publishedIdeas(page: $page, per: $per, userId: $userId) {
    nodes {
      id
      name
      ideaTags {
        id
        name
      }
    }
    pageInfo {
      currentPage
      isFirst
      isLast
      nextPage
      per
      prevPage
      totalCount
      totalPages
    }
  }
}

query GetSuggestIdeas($ideaId: ID!) {
  suggestIdeas(ideaId: $ideaId) {
    nodes {
      id
      name
      user {
        image
      }
      ideaTags {
        id
        name
      }
    }
    title
  }
}
