query GetIdea($id: ID!) {
  idea(id: $id) {
    id
    name
    icon
    background
    goal
    issue
    wishFunction
    hypothesis
    target
    monetize
    similar
		note
    createdAt
    updatedAt
    userId
    user {
      id
      name
      icon
    }
    comments {
      id
      description
      createdAt
      user {
        name
        icon
      }
    }
    ideaTags {
      id
      name
    }
  }
}

query GetIdeas($searchCondition: SearchCondition, $sort: SortCondition) {
  ideas(searchCondition: $searchCondition, sort: $sort) {
    nodes {
      id
      name
      commentsNum
      difficulty
      likesNum
      view
      updatedAt
      publishedAt
      user {
        id
        name
        icon
      }
      ideaTags {
        name
      }
      team {
        status
        membersNum
      }
    }
    pageInfo {
      currentPage
      isFirst
      isLast
      nextPage
      per
      prevPage
      totalCount
      totalPages
    }
  }
}

query GetHotIdeas {
  hotIdeas {
    id
    name
    user {
      icon
    }
  }
}

query GetDeployedIdeas {
  deployedIdeas {
    id
    name
    user {
      icon
    }
  }
}

query GetActiveTeamIdeas {
  activeTeamIdeas {
    id
    name
    user {
      icon
    }
  }
}

mutation CreateIdea($input: CreateIdeaInput!) {
  createIdea(input: $input) {
    idea {
      userId
      name
      background
      goal
      target
    }
    success
  }
}

mutation UpdateIdea($input: UpdateIdeaInput!) {
  updateIdea(input: $input) {
    idea {
      id
      name
      background
      goal
      target
    }
    success
  }
}

mutation DestroyIdea($input: DestroyIdeaInput!) {
  destroyIdea(input: $input) {
    success
  }
}
