query GetIdea($id: ID!) {
  idea(id: $id) {
    id
    name
    note
    goal
  }
}

query GetIdeas($searchCondition: SearchCondition) {
  ideas(searchCondition: $searchCondition) {
    nodes {
      id
      name
      commentsNum
      difficulty
      likesNum
      view
      publishedAt
      user {
        id
        name
        icon
      }
      ideaTags {
        name
      }
      team {
        status
      }
    }
    pageInfo {
      currentPage
      isFirst
      isLast
      nextPage
      per
      prevPage
      totalCount
      totalPages
    }
  }
}

query GetHotIdeas {
  hotIdeas {
    id
    name
    user {
      icon
    }
  }
}

query GetDeployedIdeas {
  deployedIdeas {
    id
    name
    user {
      icon
    }
  }
}

query GetActiveTeamIdeas {
  activeTeamIdeas {
    id
    name
    user {
      icon
    }
  }
}

mutation CreateIdea($input: CreateIdeaInput!) {
  createIdea(input: $input) {
    idea {
      userId
      name
      background
      goal
      target
    }
    success
  }
}

mutation UpdateIdea($input: UpdateIdeaInput!) {
  updateIdea(input: $input) {
    idea {
      id
      name
      background
      goal
      target
    }
    success
  }
}

mutation DestroyIdea($input: DestroyIdeaInput!) {
  destroyIdea(input: $input) {
    success
  }
}

