query GetLikes {
  likes {
    id
    userId
    likableType
    likableId
  }
}

query GetLikesByUser($userId: ID!) {
  likesByUser(userId: $userId) {
    id
    userId
    likableType
    likableId
  }
}

query GetLikesForEntity($likableType: String!, $likableId: ID!) {
  likesForEntity(likableType: $likableType, likableId: $likableId) {
    id
    userId
    likableType
    likableId
  }
}
