query GetLikes($userId: ID!) {
  likes(userId: $userId) {
    id
    userId
    likableType
    likableId
  }
}

mutation CreateLike($input: CreateLikeInput!) {
  createLike(input: $input) {
    like {
      userId
      likableType
      likableId
    }
    success
  }
}

mutation DestroyLike($input: DestroyLikeInput!) {
  destroyLike(input: $input) {
    success
  }
}
