query GetNotificationConfig($userId:ID!){
  notificationConfig(userId: $userId){
    userId
    commentEmail
    commentWeb
    draftRemindEmail
    eventEmail
    heartEmail
    heartToCommentWeb
    heartWeb
    teamJoinEmail
    teamJoinWeb
    teamMessageEmail
    voteWeb
    weeklyEmail
  }
}

mutation UpdateNotificationConfig($input: UpdateNotificationConfigInput!){
  updateNotificationConfig(input: $input){
    success
    notificationConfig{
      commentEmail
      commentWeb
      draftRemindEmail
      eventEmail
      heartEmail
      heartToCommentWeb
      heartWeb
      teamJoinEmail
      teamJoinWeb
      teamMessageEmail
      voteWeb
      weeklyEmail
    }
  }
}
