query GetNotifications {
  notifications {
    id
    checked
    notificatableId
    notificatableType
    createdAt
    ideaId
    idea {
      id
      name
    }
    visitor {
      name
      image
    }
  }
}

query GetLatestNotifications {
  latestNotifications {
    id
    checked
    notificatableId
    notificatableType
    createdAt
    ideaId
    idea {
      id
      name
    }
    visitor {
      name
      image
    }
  }
}
