query GetNotificationConfig($userId:ID!){
  notificationConfig(userId: $userId){
    userId
    commentEmail
    draftRemindEmail
    eventEmail
    heartEmail
    teamJoinEmail
    teamLeaveEmail
    teamMessageEmail
    weeklyEmail
  }
}

mutation UpdateNotificationConfig($input: UpdateNotificationConfigInput!){
  updateNotificationConfig(input: $input){
    success
    notificationConfig{
      commentEmail
      draftRemindEmail
      eventEmail
      heartEmail
      teamJoinEmail
      teamLeaveEmail
      teamMessageEmail
      weeklyEmail
    }
  }
}
