query GetNotifications($page: Int, $per: Int) {
  notifications(page: $page, per: $per) {
    nodes {
      id
      checked
      notificatableId
      notificatableType
      createdAt
      ideaId
      idea {
        id
        name
      }
      visitor {
        id
        name
        image
      }
    }
    pageInfo {
      totalCount
      totalPages
    }
  }
}

query GetLatestNotifications {
  latestNotifications {
    id
    checked
    notificatableId
    notificatableType
    createdAt
    ideaId
    idea {
      id
      name
    }
    visitor {
      name
      image
    }
  }
}
