query GetTeam($id: ID!) {
  team(id: $id) {
    id
    ownerId
    ideaId
    status
    requirement
    offer
    membersNum
    idea {
      id
      name
      iconUrl
    }
    owner {
      name
      definition
      image
    }
  }
}

query GetTeams {
  teams {
    id
    ownerId
    ideaId
    status
    requirement
    offer
    membersNum
  }
}

mutation createTeam($input: CreateTeamInput!) {
  createTeam(input: $input) {
    team {
      id
      ownerId
      status
      requirement
      offer
      membersNum
    }
    success
    errors
  }
}

mutation updateTeam($input: UpdateTeamInput!) {
  updateTeam(input: $input) {
    team {
      id
      ownerId
      status
      requirement
      offer
      membersNum
    }
    success
    errors
  }
}

mutation DestroyTeam($input: DestroyTeamInput!) {
  destroyTeam(input: $input) {
    success
    errors
  }
}

mutation JoinTeam($input: JoinTeamInput!) {
  joinTeam(input: $input) {
    teamUser {
      teamId
      userId
    }
    success
    errors
  }
}

mutation LeaveTeam($input: LeaveTeamInput!) {
  leaveTeam(input: $input) {
    success
    errors
  }
}
