query GetTeam($id: ID!) {
  team(id: $id) {
    id
    ownerId
    ideaId
    status
    requirement
    offer
    membersNum
  }
}

query GetTeams {
  teams {
    id
    ownerId
    ideaId
    status
    requirement
    offer
    membersNum
  }
}

mutation createTeam($input: CreateTeamInput!) {
  createTeam(input: $input) {
    team {
      id
      ownerId
      status
      requirement
      offer
      membersNum
    }
    success
  }
}

mutation updateTeam($input: UpdateTeamInput!) {
  updateTeam(input: $input) {
    team {
      id
      ownerId
      status
      requirement
      offer
      membersNum
    }
    success
  }
}
