import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import testQuery from '@/components/test'
import MainVisual from '@/components/features/MainVisual'
import NewIdea from '@/components/features/NewIdea'
import SearchTags from '@/components/features/SearchTags'
import Philosophy from '@/components/features/Philosophy'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data, loading } = testQuery()

  if (loading) return <p>Loading...</p>

  return (
    <>
      <Head>
        <title>ideee | アイディー</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainVisual />
      <NewIdea />
      <SearchTags />
      <Philosophy />
    </>
  )
}
