import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import testQuery from '@/components/test'
import MainVisual from '@/components/features/MainVisual'
import SearchTags from '@/components/features/SearchTags'
import Philosophy from '@/components/features/Philosophy'
import TeamIdea from '@/components/features/TeamIdea'
import RealizedIdea from '@/components/features/RealizedIdea'
import GetHotIdeas from '@/components/features/GetHotIdeas'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data, loading } = testQuery()
  const [LSLoggedIn, setLSLoggedIn] = useState(false)

  useEffect(() => {
    setLSLoggedIn(localStorage.getItem('loggedIn') === 'true')
  }, [])
  if (loading) return <p>Loading...</p>

  return (
    <>
      <Head>
        <title>ideee | アイディー</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!LSLoggedIn && <MainVisual />}
      <GetHotIdeas />
      <SearchTags />
      {LSLoggedIn && <TeamIdea />}
      {LSLoggedIn && <RealizedIdea />}
      {!LSLoggedIn && <Philosophy />}
    </>
  )
}
