require 'tzinfo'
require 'date'

# Create a TimeZone object for the desired timezone
tz = TZInfo::Timezone.get('Asia/Tokyo')
# Get the current time in that timezone
current_time = tz.now
current_date = current_time.to_date

has_graphql_changes = !git.modified_files.grep(/graphql/).empty?
has_models_changes = !git.modified_files.grep(/models/).empty?
has_test_changes = !git.modified_files.grep(/spec/).empty?
has_api_changes = !git.modified_files.grep(/api/).empty?
has_logic_changes = has_graphql_changes || has_models_changes

# WIPのお知らせ
warn 'PRはWIPでまだ作業中のようです' if github.pr_title.include? 'WIP'

# ===== PR size =====
warn 'PRがが大きすぎます。PRの分割を考えましょう' if git.lines_of_code > 400
number_of_commits = git.commits.size
warn 'コミットが15を超えてます。PRの分割を検討ください' if number_of_commits > 15

# PRが3日以上開かれているか
pr_created_at = github.pr_json['created_at'].to_s
days_old = (current_date - Date.parse(pr_created_at)).to_i
warn 'このPRはすでに3日以上開かれています' if days_old > 3

# ===== 対応が必要なお知らせ =====
has_schema_changes = git.modified_files.include?('db/schema.rb')
warn 'このPRはデータベーススキーマを変更しています。マイグレーションをお忘れなく' if has_schema_changes
warn('Gemfileが変更されました。bundle installをお忘れなく') if git.modified_files.include?('Gemfile')

# ===== Test =====
warn('ロジックに変更があるようですが、テストが書かれていません') if has_logic_changes && has_test_changes

# binding.pryとputsの消し忘れチェック
if has_api_changes
  git.diff.each do |chunk|
    diffs = chunk.patch.lines
    fail('binding.pryがコードの変更部分で検出されました。') if diffs.include?('binding.pry')
    fail('binding.pryがコードの変更部分で検出されました。') if diffs.include?('puts ')
  end
end
