version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: "Asia/Tokyo"
    ports:
      - "4306:3306"
  web:
    build: .
    command: bash -c "sleep 20 && rm -f tmp/pids/server.pid && bundle exec rails s -p 3010 -b '0.0.0.0'"
    volumes:
      - .:/ideee
      - bundle_data:/usr/local/bundle
    ports:
      - "3010:3010"
    depends_on:
      - db
    env_file:
      - web-variables.env
    environment:
      REDIS_URL: redis://redis:6379
  redis:
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - 6379:6379
# 永続化領域
volumes:
  bundle_data:
  redis:
  rails_tmp_cache:
