# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 7.0.8'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5'
# Use Puma as the app server
gem 'puma', '~> 5.6'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6' # NOTE: active_admin.scss に必要
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.6'

gem 'devise'
gem 'jwt'

# Use Active Storage variant
gem 'image_processing', '~> 1.12'

gem 'aws-sdk-s3', require: false
gem 'carrierwave'
# GraphqlがデフォルトでFormDataを送れないのでbase64に対応
gem 'carrierwave-base64'
gem 'fog-aws'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

gem 'dotenv-rails'

gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth-twitter'

gem 'google-api-client'

gem 'cloudinary'

gem 'devise-i18n'
gem 'rails-i18n'

gem 'enum_help'
gem 'faker'

gem 'kaminari'
gem 'slack-notifier'

gem 'sendgrid-ruby' # メール送信

gem 'activeadmin' # 管理画面

# uncomment out when you need
# gem 'stripe'

gem 'sidekiq'

# twitterV2用設定
gem 'oauth'
gem 'typhoeus'

# エラー関係
gem 'rack-timeout'

# 検索メソッド
gem 'ransack', '>= 4.0.0'

# Rubyバージョンアップで対応

# Psych 4.0以降の破壊的変更に対処
gem 'matrix', '~> 0.4.2'
gem 'net-smtp', require: false
gem 'psych'

# js-compile用のSprocketのために設定
gem 'uglifier'

# カウントのキャッシュ設定
gem 'counter_culture'

gem 'graphql'

gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  # Test
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'spring-commands-rspec'

  # Debug
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'

  # rubocop
  gem 'rubocop', require: false
  gem 'rubocop-graphql', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false

  # PRの自動チェック
  gem 'danger'
  gem 'faraday-retry'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'listen', '~> 3.3'
  gem 'rack-mini-profiler', '~> 2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'brakeman'
  gem 'bullet'
  gem 'letter_opener_web'
  gem 'seed-fu'

  # ER図の自動生成
  gem 'rails-erd'

  # TODO: graphiqlを削除する場合には、以下のgemも削除する
  gem 'graphiql-rails'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :production do
  # stackprof: プロファイリングツール
  gem 'stackprof'
  # sentry-ruby: SentryのRuby用ライブラリ
  gem 'sentry-ruby'
  # sentry-rails: SentryのRails用ライブラリ
  gem 'sentry-rails'
end
