name: post analytics to slack

on:
  schedule:
    - cron: '0 22 * * *'  # 日本時間に調整

jobs:
  post_analytics:
    name: Run rake task
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true

    # Authenticate with Heroku CLI
    - name: Authenticate with Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku auth:token

    # Run the Heroku command
    - name: Run rake task on Heroku
      run: |
        heroku run bundle exec rake report_analytics:send_to_slack -a ideee-tech
