name: brakeman

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'front/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  brakeman:
    name: Run brakeman test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RAILS_ENV: test

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true
        working-directory: ./api

    - name: Run Brakeman
      run:  |
        cd api
        bundle exec brakeman
