name: rspec

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'front/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  rspec:
    name: Run rspec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup docker and run tests
      shell: bash
      run: |
        cd api
        docker compose build --no-cache
        docker compose run --rm -e RAILS_ENV=test -e SECRET_KEY_BASE=test_secret_key_base_for_ci web bundle install
        docker compose run --rm -e RAILS_ENV=test -e SECRET_KEY_BASE=test_secret_key_base_for_ci web bundle exec rails db:create
        docker compose run --rm -e RAILS_ENV=test -e SECRET_KEY_BASE=test_secret_key_base_for_ci web bundle exec rails db:migrate
        docker compose run --rm -e RAILS_ENV=test -e SECRET_KEY_BASE=test_secret_key_base_for_ci web bundle exec rspec
      env:
        RAILS_ENV: test
        MYSQL_HOST: db
