# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup docker
      shell: bash
      run: |
        docker-compose build
        docker-compose run web rails action_text:install
        docker-compose run web rails db:create
      env:
        RAILS_ENV: test
        MYSQL_HOST: db

    - name: Rspec
      run:  |
        docker-compose run web bundle exec rspec --exclude-pattern "spec/requests/*_spec.rb"
      env:
        RAILS_ENV: test

    - name: Brakeman
      run:  |
        docker-compose run web bundle exec brakeman
      env:
        RAILS_ENV: test

    - name: Rubocop
      run:  |
        docker-compose run web bundle exec rubocop -a
      env:
        RAILS_ENV: test

  # ER図の自動作成
  create_er:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: development
      DB_NAME: ideee_development

    services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    steps:
      - name: make schemaspy.properties
        run: echo -e "
          schemaspy.t=mysql\n
          schemaspy.dp=\n
          schemaspy.host=db\n
          schemaspy.port=3306\n
          schemaspy.db=$DB_NAME\n
          schemaspy.u=root\n
          schemaspy.p=\n
          schemaspy.o=\n
          schemaspy.s=$DB_NAME\n
          " > /tmp/schemaspy.properties
      - name: Prepare a dir for schemaspy output
        run: mkdir -m 777 /tmp/output
      - name: run schemaspy
        run: docker run --net=${{ job.container.network }} -v "/tmp/output:/output" -v "/tmp/schemaspy.properties:/schemaspy.properties" schemaspy/schemaspy:latest -rails
      - name: upload er
        run: echo "/tmp/outputにER図が出力されているのでs3とかにアップロードしてね"
